@startuml

struct user
{
  + name : String
  + role : RoleEnum
}

struct message
{
  + from : User
  + type : MessageType
  + content : String || file
}

struct file
{
}

enum RoleEnum
{
  USER
  MODERATOR
  ADMINISTRATOR
}

enum MessageType
{
  GENERAL_CHAT
  PRIVATE_MESSAGE
  SYSTEM_INFO
}

message -- MessageType
message -- user
message -- file

user -- RoleEnum

@enduml